### PR TITLE
Update unit tests and support modern Laravel

### PR DESCRIPTION
**Pull request by heathdutton**
I have some legacy projects still using this, but they couldn't be upgraded to Laravel 6 as a result. This should get us over the hurdle.

Continues & replaces #22

### CODE REVIEW

**Comment by nonoesp** [comment]
@heathdutton this is super useful — thanks for your work!

**Comment by heathdutton** [comment]
I have nothing more to merge at the moment. But haven't had time to test this much either.

**Comment by heathdutton** [comment]
Just discovered the route that is added by default. That's not cacheable because it uses a closure... That should be refactored to use a controller. For me I'm just disabling the routes since I don't need it, but if someone wants to follow up with that :)...

**Comment by heathdutton** [comment]
Ready to merge.

**Comment by nonoesp** [comment]
This is great - thanks! 🥳

**Pull request merged**
